fakes/fake_sigar.go
sigar_windows_test.go

Requested by https://github.com/elastic/beats/pull/620

Remove cloudfactory dependency

---

.appveyor.yml

Add a `.appveyor.yml` so that `elastic/gosigar` is tested on Windows.

Adding AppVeyor config file

---

README.md
sigar_openbsd.go

Implement CpuList for OpenBSD

---

.appveyor.yml
.travis.yml

Update Golang version to 1.6.2

---

sigar_freebsd.go

This follows-up on #33 by adding the missing changes (I had these uncommitted in my working tree, sorry for the inconvenience).

Fix the FreeBSD build.

---

README.md
sigar_freebsd.go

See #43. This function isn't working so I'm removing it.

Remove freebsd implementation of ProcFDUsage - #43

---

sigar_freebsd.go

Fixes https://github.com/elastic/gosigar/issues/43.
@andrewkroh can you check this and verify it works on your system?

Add a working implementation of ProcFDUsage for FreeBSD.

---

sigar_darwin.go

Check errors before using the result

---

CHANGELOG.md
sigar_windows.go
sys/windows/ntquery.go

- Fixes #56 (ProcStatus.Username fails on Windows XP).
- Fixes #57 (CpuList fails on 32-bit Windows).

Fix issues on 32-bit Windows

---

sigar_openbsd.go

Add missing stub method for OpenBSD.

Add missing method for OpenBSD

---

CHANGELOG.md
psnotify/psnotify_linux.go
sys/endian.go
sys/linux/inetdiag.go
sys/linux/netlink.go
sys/linux/netlink_test.go

Hi ,
This is with reference #73 (comment)
Added support for big endian. Please review.

Adding support for big endian to gosigar

---

CHANGELOG.md

Add changelog to prepare relase 0.9.0

Changelog for 0.9.0

---

CHANGELOG.md

Preparing 0.10.0 release.
I have moved #112 from fixed to added section as it was not actually so broken before.

Changelog 0.10.0

---

CHANGELOG.md

Changelog 0.10.1

---

CHANGELOG.md

Accidentally linked the beats issue instead of the gosigar PR

Fix changelog PR link

---

CHANGELOG.md

Update CHANGELOG for 0.10.3

---

sigar_interface.go

Just trying to clean up this up a bit. We call this code a lot from beats, so I'd like to start adding godocs so it's at least a tad easier for those of us with IDEs that leverage godocs.

Add godoc to interface file

---

sigar_darwin.go
sigar_darwin_386.go
sigar_darwin_amd64.go

fix for issue undefined type syscall.Timeval32 Usec and Sec methods #127

---

.appveyor.yml
.travis.yml
CHANGELOG.md
examples/ss/ss.go

Use stdlib log in ss example

---

.appveyor.yml
.travis.yml

Remove the dep because it no longer exists.

Remove dependency on gotestcover

---

CHANGELOG.md

Changelog updates for 0.12 release

Fix up changelog entries for release

---

.ci/jobs/defaults.yml
.ci/jobs/main.yml

Jenkins Job Builder job definition. it is only the  JJBB files from  https://github.com/elastic/gosigar/pull/153 to allow to test the pipeline alone.

ci: JJBB job definition

---

.ci/Jenkinsfile

Add labels for the mac on ARM and x86
1.16 supports MacOS on arm64 but 1.15 does not support it

[CI] Use MacOS for x86_64 and arm64

---

CHANGELOG.md

Release 0.14.1
