sigar_windows.go

Add a deferred close for the handle returned by CreateToolhelp32Snapshot on Windows. The handle points to a snapshot of the process'es information and was previously being leaked when getting ProcState.

Fix Windows handle leak 

---

sigar_windows.go

Supporting patch for https://github.com/elastic/topbeat/pull/130
Get CPUList fails because it has a panic(). Suppressing it to get topbeat working.

Merge fix to stop failures on get CPUList

---

concrete_sigar_test.go
sigar_interface_test.go
sigar_linux.go
sigar_linux_test.go

Hello,
This patch allows for spaces in process names on Linux.
Because everything was split on space, the process name would get truncated if it had spaces. I picked this up in Topbeat, where my `starman worker` processes were coming in as `starma`. This also messes up all the later fields in `/proc/[pid]/stat`, since they are all getting sliced out by position, and the index is off in this case.
I've not written a byte of Go before, so please forgive this patch. Hopefully you get the gist of it though.
Thanks.

Support spaces in process names.

---

examples/df.go
examples/free.go
examples/ps.go
examples/uptime.go

Even if `elastic/gosigar` is to be merged into `cloudfoundry/gosigar` at some point, it's helpful right now to build the examples against the "local" package.

use the elastic/gosigar package in examples

---

sigar_windows.go
sigar_windows_test.go

Implements ProcArgs.Get for Windows. It uses a WMI query to obtain a process'es command line (same as #1 does).

Implement ProcArgs.Get for Windows

---

sigar_interface.go
sigar_windows.go
sigar_windows_test.go

When collecting process information in windows, it is sometimes useful to know the process identity to disambiguate like process (web sites) or identify problem users on a system.
This can be implemented fairly simply with the win32 api bindings in go.
This is related to the topbeats issue elastic/beats#590 and elastic/topbeat#36, basically enables a simple call to gosigar from topbeat to implement.

Add GetProcCredName implementation to windows gosigar

---

.travis.yml
sigar_darwin.go
sigar_linux.go
sigar_test.go

The PR enhances gosigar to set the `ProcState.Username` value for Linux and Darwin (Mac OSX).
elastic/topbeat#36
Linux reference: https://www.kernel.org/doc/Documentation/filesystems/proc.txt

Set ProctState.Username on darwin and linux

---

examples/df/df.go

While were working on an OpenBSD backend for gosigar I noticed the df example would show my partitions were terabytes in size instead of gigabytes. I confirmed the same behaviour on OS X. The attached patch fixes it by dropping the extra multiplication by 1024.

Fix output of the df example where sizes were off by factor 1024

---

sigar_darwin.go

The original issue appears to have been: https://github.com/golang/go/issues/6588 , but that was resolved in Go 1.3.
I've verified the workaround is no longer required on `go1.6 darwin/amd64` and in the upcoming OpenBSD backend on `go1.5.3 openbsd/amd64`

remove getfsstat wrapper, the original issue has since been resolved

---

sigar_openbsd.go
sigar_unix.go

currently implemented are:
- FileSystemList
- Cpu
- Mem
- LoadAverage
- Uptime
- FileSystemUsage
- Swap
This is enough to bring basic topbeat functionality to OpenBSD:
```
{
"@timestamp": "2016-04-04T12:51:08.016Z",
"beat": {
"hostname": "basalt.jasper.la",
"name": "basalt.jasper.la"
},
"fs": {
"avail": 3857862656,
"device_name": "/dev/sd0a",
"files": 545662,
"free": 4069398528,
"free_files": 542408,
"mount_point": "/",
"total": 4230739968,
"used": 161341440,
"used_p": 0.04
},
"type": "filesystem"
}
{
"@timestamp": "2016-04-04T12:51:08.016Z",
"beat": {
"hostname": "basalt.jasper.la",
"name": "basalt.jasper.la"
},
"fs": {
"avail": 4682117120,
"device_name": "/dev/sd0g",
"files": 1065342,
"free": 5104588800,
"free_files": 789403,
"mount_point": "/cvs",
"total": 8449456128,
"used": …
```

Initial OpenBSD support

---

README.md

I added a table of the features implemented by OS. This includes the OpenBSD features that are currently in PR #22.

Add table of implemented features by OS

---

sigar_darwin.go
sigar_darwin_test.go
sigar_interface.go
sigar_linux.go
sigar_linux_test.go

Added ability to return process group ID (pgid) for Darwin and Linux versions, with the view to add this to Topbeat as well.

Support process group ID (pgid) for Darwin and Linux

---

concrete_sigar.go
concrete_sigar_test.go
sigar_darwin.go
sigar_interface.go
sigar_linux.go
sigar_linux_test.go
sigar_openbsd.go
sigar_windows.go

Add support for #29.
I have implemented the initial logic for Linux and just wanted to get some input to make sure I'm on the right track before I move on to attempting some of the other OSes.  A few things of note / questions:
1. Also, I'm not sure what to do what to do when reading `/proc/{PID}/fd` fails which is will for root processes if run as not root.  Currently, it just returns 0 for the open count.  I think this maybe the best route, but I am not sure.
2. I assume I should also add tests for the new logic?
3. Since we don't want the FD metrics reported by the beat if it's not implemented for the OS, I think instead of returning nil I should through an error in the unimplemented functions?

Added general file descriptor logic and implemented for linux

---

sigar_freebsd.go
sigar_linux.go
sigar_linux_common.go
sigar_unix.go

This implementation requires to mount the Linux compatibility /proc
filesystem in /compat/linux/proc. Check the FreeBSD handbook for
details.

Add support for FreeBSD.

---

cgroup/util.go
cgroup/util_test.go

The code for parsing the /proc/[pid]/mountinfo file did not account for some optional fields that could be present. This enhances the parser to handle lines that contain additional optional fields.
This will address elastic/beats#2200.

Improve /proc/[pid]/mountinfo parser

---

sigar_darwin.go

Errors were ignored in fairly dangerous places, which could result
in infinite loops. Potential fix for elastic/beats#2747.

Improve error handling on darwin

---

sigar_windows.go

Fixing https://github.com/elastic/beats/issues/2653
On Windows, set the actual free memory equal with the free memory.

Fix actual free memory on Windows

---

CHANGELOG.md
sigar_windows.go
syscall_windows.go

Gosigar requests PROCESS_ALL_ACCESS permission but the operation that it performs, GetProcessMemoryInfo, requires only PROCESS_QUERY_INFORMATION and PROCESS_VM_READ. gosigar should only request the permissions that it requires.
In other parts of gosigar it requests PROCESS_QUERY_INFORMATION, but in Windows Vista and newer there is a more limited privilege we can request called PROCESS_QUERY_LIMITED_INFORMATION. This can be used for GetProcessTimes, GetProcessImageFileName, and GetExitCodeProcess. It cannot be used for OpenProcessToken.

Request lowest access privilege required in Windows OpenProcess calls

---

CHANGELOG.md
sigar_interface_test.go
sigar_windows.go

This converts the process creation time from Windows epoch to milliseconds since unix epoch. A test was added to sanity check the StartTime value.
> Process creation and exit times are points in time expressed as the amount of time that has elapsed since midnight on January 1, 1601 at Greenwich, England.
Source: https://msdn.microsoft.com/en-us/library/windows/desktop/ms683223

Fix ProcTime.StartTime on Windows

---

CHANGELOG.md
README.md
sigar_darwin.go
sigar_interface.go
sigar_interface_test.go
sigar_linux_common.go
sigar_openbsd.go
sigar_windows.go

This PR adds the ability to retrieve the environment variables used
to start a process. It is implemented for Linux, OS X, and FreeBSD.
Neither Windows nor OpenBSD are implemented at this time.
Closes #61

Add sigar.ProcEnv for getting a process's environment

---

.gitignore
.travis.yml
CHANGELOG.md
examples/audit/audit.go
sys/linux/audit.go
sys/linux/audit_test.go
sys/linux/netlink.go
sys/linux/netlink_test.go

Added `AuditClient` for communicating to the Linux kernel's audit interface
via netlink.

Add AuditClient for communicating to the Linux kernel

---

CHANGELOG.md
sigar_linux_common.go
sigar_linux_test.go

Use MemAvailable when it's available on Linux 3.14+ kernel, otherwise calculate it as free memory plus the caches and buffers.
(Fixes https://github.com/elastic/beats/issues/4202)

Use MemAvailable when it's available on Linux 3.14+ kernel

---

CHANGELOG.md
sigar_windows.go

This issue affected Windows Vista and newer. During the `init()` phase a WMI call was made to get the system boot time. If WMI wasn't fully up the call would hang which blocked the entire application from initializing.

Fix hang during init on Windows if WMI is unavailable

---

CHANGELOG.md
sigar_windows.go

Cherry-pick of PR #74 to 0.2 branch. Original message:
> Fix hang during init on Windows if WMI is unavailable
>
> This issue affected Windows Vista and newer. During the `init()` phase a WMI call was made to get the system boot time. If WMI wasn't fully up the call would hang which blocked the entire application from initializing.

Cherry-pick #74 to 0.2: Fix hang during init on Windows if WMI is unavailable

---

CHANGELOG.md
sigar_interface_test.go

When working on #78, I was hit by a test failing on linux (debian host)
Our code is triming values so we need to adjust the test code to make
sure we also trim values before doing the comparison.
Example:
```
expected: "${debian_chroot:+($debian_chroot)}\\u@\\h:\\w\\$ "
actual: "${debian_chroot:+($debian_chroot)}\\u@\\h:\\w\\$"
```

MINOR: trim environment variable values

---

CHANGELOG.md
sigar_darwin.go

Under some circonstance the code can fail, the root cause is not clear
at the moment, but we should still make the code more robust when
retrieving information for a specific process.
The problem is the `bytes.SplitN` can return an array of one element
making the process panic when we access the other element.
This commit make the code a bit more robust and check to make sure we
successfully retrieved 2 elements instead of one and return an error
if it failed.
Reference: elastic/beats#5337

MINOR: kern_procargs more robust on darwin

---

CHANGELOG.md
sigar_freebsd.go
sigar_openbsd.go
sigar_stub.go
sigar_unix.go

* remove netbsd from `sigar_unix` as it is not supported
* add `sigar_stub` to provide stubs for unsupported functions
* add stubs for freebsd and fix openbsd for `ProcTime.Get`
These changes are required by https://github.com/elastic/beats/pull/5545

Changes to support CPU usage metric in Beats

---

CHANGELOG.md
sigar_linux_common.go
sigar_linux_test.go

- Refactor the ProcState code that parses /proc/[PID]/stat to allow any characters between the opening and closing parentheses of the comm field.
- This also improves the error handling in ProcState.Get. Previously errors from `strconv.Atio` were not checked.
- Improved the test for ProcState to validate all fields.
- Fix bug in test code that generates fake /proc/pid/stat data. It skipped "19" causing an off by one issue.
Fixes #81

Fix ProcState parsing for process names with parantheses

---

CHANGELOG.md
sigar_linux_common.go
sigar_linux_test.go

I think this  obviously must be fixed. directly cause system/memory metrics fetching incorrect

Fix incorrect Mem.Used calculation

---

CHANGELOG.md
sigar_stub.go

From now on
* `CpuList`
* `ProcState`
* `ProcExe`
* `ProcMem`
* `ProcFDUsage`
* `ProcEnv`
* `ProcList`
* `ProcArgs`
can be called from source files not protected by conditional builds in Beats. 
This is required by https://github.com/elastic/beats/pull/5545

add process stubs for unsupported OSes

---

sigar_freebsd.go

This should not have been added because the common implementation is used.

Use the common version of Get(pid)

---

CHANGELOG.md
cgroup/blkio.go
cgroup/cpu.go
cgroup/cpuacct.go
cgroup/memory.go
cgroup/util.go

While reviewing this code I noticed some missing EOF error checks in the bufio.Scanner usage as well as a few missing Close() calls on file handles.

Add missing error checks and file handle closes

---

CHANGELOG.md
concrete_sigar.go
concrete_sigar_test.go
sigar_interface.go
sigar_stub.go
sigar_unix.go
sigar_windows.go

To retrieve CPU usage time in millis in Beats, `getrusage` is added.
On Unix it is fully supported. On Windows only system and user time retrieval is implemented.

Add getrusage for Unix and partially for Windows

---

CHANGELOG.md
README.md
concrete_sigar.go
sigar_darwin.go
sigar_freebsd.go
sigar_interface.go
sigar_linux.go
sigar_linux_common.go
sigar_linux_test.go
sigar_openbsd.go
sigar_stub.go
sigar_windows.go

Add initial support for huge TLB pages on Linux, as requirement for https://github.com/elastic/beats/issues/6351.

Add support for huge TLB pages on Linux

---

sigar_linux_common.go

Panics have been reported when reading from proc files, this shouldn't happen, but while root cause is found we can workaround the issue recovering from the panic and reporting the specific procfile whose
read provoked the panic.
See https://github.com/elastic/beats/issues/6692

Recover as workaround for panic when reading proc files

---

sigar_freebsd.go
sigar_linux.go
sigar_linux_common.go

and move (self *Mem) function from sigar_linux_common to sigar_linux

Fix memory reporting on FreeBSD

---

.travis.yml

Test gosigar with latest 1.8 (to keep compatibility with this version) and 1.10 versions.

Test with newer Go versions in travis

---

examples/ss/ss_other.go

`ss` example command only works on Linux, added a dummy command so
execution of tests in other platforms works.

Add dummy command for example without implementation

---

CHANGELOG.md
sigar_windows.go

Command line can be nil, what produces errors like:
```
wmi: cannot load field "CommandLine" into a "string": unsupported type (<nil>)`
```
Change command line in receiving struct to be a pointer, so it can be converted by `wmi` if it receives a `nil`.

Command line can be nil in Win32_Process

---

CHANGELOG.md
examples/df/df.go
sigar_windows.go
sys/windows/syscall_windows.go
sys/windows/zsyscall_windows.go

`GetLogicalDriveStrings` doesn't list filesystems that are mounted with
access paths but don't have a drive letter. Use volume iterators to
list all volumes and obtain its access paths.
Reported on https://github.com/elastic/beats/issues/8916

Use volume iterators to list volumes in windows

---

CHANGELOG.md
sigar_windows.go

When running under Windows as a non-administrator  user, ProcState.Get() will fail with the error "OpenProcessToken failed for pid=XXX: Permission denied".
This is a known issue under Windows: A non-admin won't be able to access the token of most processes, regardless of privileges (i.e. SeDebugPrivilege).
This PR allows ProcState.Get to return with a missing username instead of failing completely.
I also took the opportunity to fix a case where it would be leaking a handle under an error condition.

Windows: Do not fail ProcState.Get when run by non-admin

---

CHANGELOG.md
sys/windows/syscall_windows.go
sys/windows/syscall_windows_test.go

This fixes a crash when fetching a process arguments. The command-line string read from the target process memory sometimes is not terminated.
It can cause bogus characters to be appended to the command-line or a crash.

Windows: fix a crash when splitting command-line arguments

---

CHANGELOG.md
sigar_windows.go

Uptime calculation under Windows was broken as it was interpreting the result of GetTickCount64 as a timestamp relative to UNIX epoch, but it's just an elapsed time in milliseconds.

Fix uptime calculation under Windows

---

README.md

The recent PR to add linux and Windows support for resource usage didn't add an entry to the support matrix. This adds an entry to the matrix.

Add resource usage to support matrix

---

CHANGELOG.md
sigar_darwin.go
sigar_openbsd.go
sigar_util.go
sigar_util_test.go

This is a perma-fix for https://github.com/elastic/gosigar/issues/138
Tested manually on Darwin. This is a really odd chunk of code I had to remove. My best guess is that whoever wrote this was more familiar with C than Golang, hence that oddball pointer logic.
Also cleaned up some of the darwin code, since it was really annoying.

fix odd array to string function

---

.appveyor.yml
.travis.yml
go.mod
go.sum

Travis CI was failing while testing with Go 1.10 because the latest testify requires
Go 1.13 for error.As. So by adding go.mod to use a specific testify version (and testing
with Go 1.11 minimally since we now need 'go mod') the tests should compile.

Add go.mod to fix travis build

---

CHANGELOG.md
sigar_interface.go
sigar_linux.go

See this issue for a tad more context: https://github.com/elastic/kibana/issues/77517
Right now, most front-end components that try and graph cache usage is doing it incorrectly. We're grabbing cache as a fallback to `actual` memory, so we might as well just send it along so upstream components can use it.

Report cached data in Memory

---

CHANGELOG.md
sigar_windows.go
sys/windows/syscall_windows.go
sys/windows/syscall_windows_test.go
sys/windows/zsyscall_windows.go

Not entirely sure if `go generate` is supposed to generate that many changes. I ran it on the beats Windows 2019 Vagrant VM.
Adds some of the functionality necessary for https://github.com/elastic/beats/issues/22501 -- as an example, returns `ntfs` as `SysTypeName` on the Vagrant box.

Add filesystem type support on Windows

---

CHANGELOG.md
cgroup/reader.go
cgroup/reader_test.go
cgroup/testdata/docker/proc/1/cgroup

When running in Docker, paths in `/proc/<pid>/cgroup` do not
correspond to the paths under `/sys/fs/cgroup/<subsystem>/...`
Instead, the root `/sys/fs/cgroup/<subsystem>` should be
used there. Provide an option for overridding the path,
similar to https://github.com/elastic/elasticsearch/pull/22757.
I added NewReaderOptions/ReaderOptions to avoid breaking
the API, and to minimise breakage in the future.
Required for https://github.com/elastic/beats/issues/22844

cgroup: add option to override the /sys/fs/cgroup hierarchy

---

sigar_windows.go
sys/windows/syscall_windows.go

Ignore unsupported derive types for GetVolumeInformation  function.
Issue related https://github.com/elastic/beats/issues/22501

Ignore unsupported derive types for GetVolumeInformation  function

---

.ci/jobs/folders.yml
.ci/jobs/main.yml

It defines the right directory at the JJBB level
Consistency, as other Go libs live in the target directory.
- Closes #162

chore(ci): move to the right CI folder

---

CHANGELOG.md
sigar_windows.go
sys/windows/syscall_windows.go

similar to https://github.com/elastic/gosigar/pull/159
GetVolumeInformation will fail for external drives like CD-ROM or other type with error codes as ERROR_NOT_READY. ERROR_INVALID_FUNCTION, ERROR_INVALID_PARAMETER and could be others.
The PR will report error in the logs but ignore it and move further. We consider retrieving filesystem type best efforts.
Since we introduced this calculation we are getting too many issues related to external drives, so we need to decide on one of the following behaviors:
- revert https://github.com/elastic/beats/issues/22501 which is causing these scenarios
- report error and ignore it (this is what this PR is doing, we need to handle it on the helper.go side in the beats code)
- ignore error, no report in the logs since it complicates code by adding …

Handle ERROR_INVALID_PARAMETER error for GetVolumeInformationW win32 api

---

.github/workflows/ci.yml
.github/workflows/opentelemetry.yml

- Subscribe to all workflows
- Use check-dependent-jobs to create a single status check that can be set as required
This way, the `test` check can stay as required.

Fix GH workflows

---

CHANGELOG.md
sigar_common_darwin.go

The unit tests currently fail under race on Go 1.22 on Darwin.
> go test -race -v -run TestMem
fatal error: checkptr: converted pointer straddles multiple allocations
goroutine 35 gp=0xc000104c40 m=0 mp=0x104af4d00 [running]:
runtime.throw({0x1048d66ee?, 0xc00012c7d8?})
/opt/homebrew/Cellar/go/1.22.1/libexec/src/runtime/panic.go:1023 +0x40 fp=0xc000067cc0 sp=0xc000067c90 pc=0x1046b8a20
runtime.checkptrAlignment(0x1048ca639?, 0xa?, 0x104af4d00?)
/opt/homebrew/Cellar/go/1.22.1/libexec/src/runtime/checkptr.go:26 +0x70 fp=0xc000067ce0 sp=0xc000067cc0 pc=0x1046861e0
github.com/elastic/gosigar.sysctlbyname({0x1048ca639, 0xa}, {0x10494bca0, 0xc000067e30})
/Users/ssd/src/gosigar/sigar_common_darwin.go:483 +0xa8 fp=0xc000067d60 sp=0xc000067ce0 pc=0x1048800d8 …

fix checkptr in (*Mem).Get on darwin on Go 1.22

---

.github/workflows/ci.yml

⚠️ This PR was created by an automated tool. Please review the changes carefully. ⚠️ 
NOTE: https://github.com/elastic/apm-pipeline-library has been archived in favor of 
https://github.com/elastic/oblt-actions.
Requires https://github.com/elastic/oblt-actions/pull/16 to be merged.
If there are any questions, please reach out to the @elastic/observablt-ci

github-action: use elastic/oblt-actions/check-dependent-jobs

---

sigar_linux.go
sigar_linux_common.go
sigar_linux_common_test.go

when reading /etc/mtab with long lines (>4096 bytes) reader.ReadLine() return isPrefix as true and we append the next returned line to the buffer before passing it to the handler
fixes #166 
Info @wt-io-it

fix linux readFile for long lines

---

sigar_linux.go

ioutil.ReadDir calls stat on every directory entry. These calls are not required
to count the number of file descriptors.
For a process with many open file descriptors this can be costly.
In a local benchmark on a directory with 10k files, we observe the following improvement by using (*os.File).Readdirnames directly:
```
goos: linux
goarch: amd64
pkg: github.com/elastic/gosigar
cpu: Intel(R) Xeon(R) CPU @ 2.80GHz
│   old.txt    │               new.txt               │
│    sec/op    │   sec/op     vs base                │
GetDirEntryCount-24   23.874m ± 0%   2.967m ± 0%  -87.57% (p=0.000 n=25)
│    old.txt    │               new.txt                │
│     B/op      │     B/op      vs base                │
GetDirEntryCount-24   3310.4Ki ± 0%   729.4Ki ± 0%  -77.97% (p=0.000 n=25)
│ …
```

feat: improve ProcFDUsage performance
